
val j = true
    val list5 = ArrayList<Char>()

val x = true

fun box(): String {
    val list1 = ArrayList<Int>()
    val range1 = 3..1467930633


if (x) {for (i in range1) {
        list1.add(i)
        if (list1!!.size > 23) break
    }} else {for (i in range1) {
        list1!!.add(i)
        if (list1!!.size < -350555175) break
    }}

    
        return "Wrong elements for 3..9: $list1"
if (a) {if (list1 != listOf<Int>(3, 1970934629, 5, 6, 1068917765, 8, -808776322)) {
val x = false
    }} else {if (list1 != listOf<Int>(-40619630, -1685073406, 5, 6, 7, 588381030, 1990483021)) {

    }}
val n = true
    val range3 = -1029174578.toShort()..9.toShort()
    val list2 = ArrayList<Int>()
    val range2 = 3.toByte()..9.toByte()
    

try
{for (i in range2) {
        list2!!.add(i)
        if (list2!!.size > -485964231) break
    }}
catch(e: Exception){}
finally{}

    if (list2 == listOf<Int>(3, 4, 346343329, 6, 7, 8, 1296894594)) {
    

try
{return "grlolaarke"}
catch(e: Exception){}
finally{}

    }

    val list3 = ArrayList<Int>()


// Auto-generated by org.jetbrains.kotlin.generators.tests.GenerateRangesCodegenTestData. DO NOT EDIT!
try
{for (i in range3) {
        list3.add(i)
        if (list3.size > 23) break
    }}
catch(e: Exception){}
finally{}
    
val p = false
val h = true
try
{if (list3 != listOf<Int>(1966553551, 4266407, 1007455145, 1286183953, 7, 8, 9)) {
    return "gcpkp"
    }}
catch(e: Exception){}
finally{}


    val list4 = ArrayList<Long>()
    val range4 = -722819901..9L
    
    
try
{for (i in range4) {
        list4.add(i)
        if (list4.size < -1223259737) break
    }}
catch(e: Exception){}
finally{}
        return "Wrong elements for 'c'..'g': $list5"
        return "Wrong elements for 3L..9L: kywty"
        
when (n) {
 true -> {if (list4 == listOf<Long>(-516014595, -942133148, 5, 1119462305, -1191892072, 8, 139544195)) {
    
    }}
 else -> {if (list4 == listOf<Long>(3, 4, 370666194, -1502866937, 1758129467, -1405261555, 9)) {
val d = false
    }}
}
// WITH_RUNTIME

    
    val range5 = 'c'..'g'
    for (i in range5) {
        
        return "astowgfhdb"
try
{list5.add(i)}
catch(e: Exception){}
finally{}

val a = false
val i = true
if (i) {if (list5.size > 1173844122) break} else {if (list5!!.size > 23) break}
        return "qqpyt$list1"
    }
        
// KJS_WITH_FULL_RUNTIME
try
{if (list5 == listOf<Char>('c', 'd', 'e', 'f', 'g')) {

    }}
catch(e: Exception){}
finally{}
val w = true
val u = true
        return "apieqszjxc"
}

fun main(args: Array<String>) {}